### ISSUE TITLE
create a home page 

### ISSUE THREAD

**Issue by eyupakbaba** [eyup170290064/hospital_management_system#1]
It ll be home page of hospital management system website.

**Comment by eyupakbaba** [comment]
I just realised that when i click 'admin' button it is not working as it should be.

![admin](https://user-images.githubusercontent.com/105799589/170232743-7c0a7585-e929-493e-9f9a-311ea666e054.PNG)

**Comment by selamikadioglu1** [comment]
Whoops! How come? As i remember i checked it and was working. You can fix it in 'header.php' file and also these sides (admin,doctor,patient) should be on the far right not next to 'HOSPITAL MANAGEMENT SYSTEM'

**Comment by eyupakbaba** [comment]
problem solved 👍
