### ISSUE TITLE
Reject doctor's job request

### ISSUE THREAD

**Issue by eyupakbaba** [eyup170290064/hospital_management_system#17]
**Doctors who applied for job will be rejected.**

**Comment by eyupakbaba** [comment]
reject button is not working! 

![reject_button](https://user-images.githubusercontent.com/105799589/171166358-05414c13-933e-4bb3-bbe5-649a1155f38c.PNG)

**Comment by selamikadioglu1** [comment]
lemme try to fix it!

**Comment by selamikadioglu1** [comment]
![prorb](https://user-images.githubusercontent.com/105221401/171167867-c4874a40-e857-4f7e-935f-e288392affb2.PNG)
