### ISSUE TITLE
edit page for doctors

### ISSUE THREAD

**Issue by eyupakbaba** [eyup170290064/hospital_management_system#24]
You will be able to see doctor details and update their salaries.

**Comment by selamikadioglu1** [comment]
Update salary form is not working! 

![salary](https://user-images.githubusercontent.com/105221401/171995094-9d604774-aad1-4b06-ae62-b5bb5308c7f1.PNG)

**Comment by eyupakbaba** [comment]
I realised that the first letter of the word 'update' has been written with capital letter. 

![fixed](https://user-images.githubusercontent.com/105799589/171995411-531d32a6-7767-44ef-b36a-7c668aac967e.PNG)
