### ISSUE TITLE
create an admin dashboard

### ISSUE THREAD

**Issue by eyupakbaba** [eyup170290064/hospital_management_system#4]

**Comment by eyupakbaba** [comment]
Even though you coded them I can't see the icons next to the names on the admin dashboard. 

![icon](https://user-images.githubusercontent.com/105799589/170245934-bb129f53-0a3d-4b2a-8933-d8e6e4049204.PNG)

**Comment by selamikadioglu1** [comment]
Icon 'link and script' addresses are missing !!!

**Comment by selamikadioglu1** [comment]
done 👍 

![header](https://user-images.githubusercontent.com/105221401/170363822-a942808a-bfc1-400e-9da2-b58059cd4424.PNG)

**Comment by eyupakbaba** [comment]
The 'commit' you did has been made by different username. That's why i deleted it. So please push a new commit.

**Comment by selamikadioglu1** [comment]
i did!
